services:
  moontv:
    image: bestrui/bestsub:v1.5.2
    container_name: ${CONTAINER_NAME}
    restart: always

    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    
    volumes:
      - ./data:/app/data
            
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
