services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3.6.2
    container_name: ${CONTAINER_NAME}
    environment:
      # ---- 通用配置 ----
      - APP_URL=${PANEL_TINYAUTH_APP_URL}
      - SECRET=${PANEL_TINYAUTH_SECRET}
      - SESSION_EXPIRY=${PANEL_TINYAUTH_SESSION_EXPIRY}
      - APP_TITLE=${PANEL_TINYAUTH_APP_TITLE}
      - OAUTH_AUTO_REDIRECT=${PANEL_TINYAUTH_OAUTH_AUTO_REDIRECT}
      - BACKGROUND_IMAGE=${PANEL_TINYAUTH_BACKGROUND_IMAGE}

      # ---- GitHub ----
      - GITHUB_CLIENT_ID=${PANEL_TINYAUTH_GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${PANEL_TINYAUTH_GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${PANEL_TINYAUTH_GITHUB_REDIRECT_URI}

      # ---- Google ----
      - GOOGLE_CLIENT_ID=${PANEL_TINYAUTH_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${PANEL_TINYAUTH_GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${PANEL_TINYAUTH_GOOGLE_REDIRECT_URI}

      # ---- Generic (示例 Linux.Do) ----
      - GENERIC_NAME=${PANEL_TINYAUTH_GENERIC_NAME}
      - GENERIC_CLIENT_ID=${PANEL_TINYAUTH_GENERIC_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${PANEL_TINYAUTH_GENERIC_CLIENT_SECRET}
      - GENERIC_AUTH_URL=${PANEL_TINYAUTH_GENERIC_AUTH_URL}
      - GENERIC_TOKEN_URL=${PANEL_TINYAUTH_GENERIC_TOKEN_URL}
      - GENERIC_USER_URL=${PANEL_TINYAUTH_GENERIC_USER_URL}

    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always
    volumes:
      - ./data:/data

networks:
  1panel-network:
    external: true
