services:
  ech0:
    image: sn0wl1n/ech0:v2.5.0
    container_name: ${CONTAINER_NAME}
    environment:
      - JWT_SECRET=${PANEL_ECH0_JWT_SECRET}
    ports:
      - "${PANEL_APP_PORT_HTTP}:6277"
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always

networks:
  1panel-network:
    external: true
